ALTER TABLE users
ADD COLUMN IF NOT EXISTS plan_id UUID;

ALTER TABLE users
ADD COLUMN IF NOT EXISTS bonus_builds INTEGER NOT NULL DEFAULT 0;

ALTER TABLE users
ADD COLUMN IF NOT EXISTS bonus_exports INTEGER NOT NULL DEFAULT 0;

ALTER TABLE users
ADD CONSTRAINT fk_users_plan
FOREIGN KEY (plan_id)
REFERENCES plans(id);